#cloud-config

package_update: true
package_upgrade: true
users:
    - name: ${prefix}
      sudo: ["ALL=(ALL) NOPASSWD:ALL"]
      groups: sudo, docker
      shell: /bin/bash
      ssh_authorized_keys:
          - "${ssh_key_1}"
          - "${ssh_key_2}"
packages:
    - fail2ban
    - docker.io
    - jq
    - prometheus-node-exporter
    - python3-pip
preserve_hostname: false
fqdn: ${fqdn}
hostname: ${fqdn}
write_files:
    - path: /etc/environment
      content: |
          POLYGON_NETWORK_NAME="${polygon_network_name}"
          POLYGON_NETWORK_CODE="${polygon_network_code}"
          BOR_MODE="${bor_mode}"
          ETH_RPC_URL="${eth_rpc_url}"
          HEIMDALL_SEEDS="${heimdall_seeds}"
          BOR_BOOTNODES="${bor_bootnodes}"
      append: true
runcmd:
    - pip3 install docker-compose
    - sed -i -e '/^Port/s/^.*$/Port ${ssh_port}/' /etc/ssh/sshd_config
    - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
    - sed -i -e '$aAllowUsers ${prefix}' /etc/ssh/sshd_config
    - mkdir -p /mnt/data/heimdall