version: "3.8"
services:
  heimdall:
    image: 0xpolygon/heimdall:0.2.11
    container_name: heimdall
    entrypoint: "/usr/local/bin/heimdalld"
    command: "start --home=/heimdall-home"
    ports:
      - "26656:26656"
      - "26657:26657"
    volumes:
      - /mnt/data/heimdall:/heimdall-home
    restart: unless-stopped
    depends_on:
      - node-exporter

  heimdall-rest-server:
    image: 0xpolygon/heimdall:0.2.11
    container_name: heimdall-rest-server
    entrypoint: "/usr/local/bin/heimdalld"
    command: "rest-server --home=/heimdall-home --node tcp://heimdall:26657"
    ports:
      - "1317:1317"
    volumes:
      - /mnt/data/heimdall:/heimdall-home
    restart: unless-stopped

  bor:
    image: 0xpolygon/bor:0.2.16
    container_name: bor
    command: >
      --datadir=/bor-home
      --port 30303
      --bor.heimdall "http://heimdall-rest-server:1317"
      --http
      --http.addr "0.0.0.0"
      --http.vhosts "*"
      --http.corsdomain "*"
      --http.port 8545
      --ipcpath /bor-home/bor.ipc
      --http.api "eth,net,web3,txpool,bor"
      --syncmode "full"
      --networkid "80001"
      --miner.gasprice "30000000000"
      --miner.gaslimit "20000000"
      --miner.gastarget "20000000"
      --txpool.nolocals
      --txpool.accountslots 16
      --txpool.globalslots 32768
      --txpool.accountqueue 16
      --txpool.globalqueue 32768
      --txpool.pricelimit "30000000000"
      --txpool.lifetime "1h30m0s"
      --maxpeers 200
      --bootnodes "enode://095c4465fe509bd7107bbf421aea0d3ad4d4bfc3ff8f9fdc86f4f950892ae3bbc3e5c715343c4cf60c1c06e088e621d6f1b43ab9130ae56c2cacfd356a284ee4@18.213.200.99:30303"
    ports:
      - "8545:8545"
      - "30303:30303"
    volumes:
      - /mnt/data/bor:/bor-home:rw
    restart: unless-stopped
    depends_on:
      - heimdall-rest-server
    labels:
      org.label-schema.group: "polygon"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: >
      --path.procfs=/host/proc
      --path.rootfs=/rootfs
      --path.sysfs=/host/sys
      --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    restart: unless-stopped
    labels:
      org.label-schema.group: "polygon-heimdall"
